name: Chrysanthemum
author: FluffyPancakes
version: 0.1a
main: me.FluffyPancakes.Chrysanthemum.Main
depend: [Vault]
commands:
   Chrysanthemum:
      description: Displays information about the plugin.
